### ISSUE TITLE
repeat et select1 (boutons radio)

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#10]
@bug lorsque l'on duplique une liste bouton de radio (pour les categories p. ex.) la première liste se décoche (mais le modèle xml est bien complété !?).

**N.B.** aucun problème avec les listes choix multiples et les listes déroulantes (utilisation de cette dernière pour le moment).

**Comment by emchateau** [comment]
La solution élaborée ensemble aujourd’hui me paraît résoudre la difficulté.
