### ISSUE TITLE
attribuer les conclusions aux experts

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#112]
Chers tous, 

Je reprends la modification de traitement des conclusions que nous avons retenue lors de notre dernière séance de travail, à savoir que les champs « conclusions » ne sont maintenant plus conditionnés au champ « dispositif de l'expertise ». Elles doivent être ajoutées manuellement par la personne qui dépouille, qui doit également préciser le(s) expert(s) lié(s) à cet avis.

Ma question porte sur l'alignement des anciennes fiches. Lorsqu'il y avait désaccord, il n'y a pas de problème logiquement puisque chaque conclusion est déjà rattachée à un expert.

Ma question porte donc sur les deux types d'expertise suivants :
- les expertises qui n'ont qu'un seul expert ;
- les expertises avec plusieurs experts qui rendent le même avis (accord).

Pour le premier cas, je ne vois pas de problème à automatiser l'attribution d'une conclusion à l'expert (logiquement il est seul à intervenir, et si conclusion il y a, elle ne peut être que la sienne ?)

Pour le second cas, il faudrait distinguer les expertises avec tiers-experts, que nous ne pourrons pas automatiser car nous avons convenu qu'il fallait les reprendre dans tous les cas (pas toujours les premiers experts, etc.). Mais pour les autres expertises sans tiers-expert, voyez-vous quelque chose qui empêcherait que nous les traitions de manière systématique ?

Ce que je ne veux pas c'est créer des erreurs par des traitements automatiques. La manière la plus simple et la plus sûre, c'est d'ajouter les champs manquants, sans les pré-remplir, mais ça signifie que nous devrons reprendre toutes les expertises concernées à la main…
@LeonoreLosserand peut-être qu'avec ta pratique tu vois des contre-indications à toute automatisation ?

Amitiés, 
Josselin.

**Comment by emchateau** [comment]
Même avis que ce tu exposes. Ne pas relier les conclusions fautivement à un expert.

**Comment by LeonoreLosserand** [comment]
Je pense qu'il vaut sans doute mieux éviter l'automatisation
Il y a souvent une dernièr phrase générale (qui renvoie le jugement de
l'affaire au juge) que je transcrit toujours et qui n'est pas attribuable à
un expert en particulier)
 bientôt
Léonore

**Comment by sardinecan** [comment]
Est-ce ce que cela veut dire qu’il vaut mieux éviter l’automatisation, même pour les expertises n’ayant qu’un seul expert ? 

Envoyé de mon iPhone

**Comment by LeonoreLosserand** [comment]
On peut dire que pour le cas où il n'y a qu'un seul expert, il n'y a pas de
pb à rattacher à un expert

Pour garder une certaine cohérence, on pourrait alors mettre toutes les
conclusions générales dans une même case à part (celles qui en appellent au
juge dans le cas d'expertises passant devant le LC ou autre institution),
après avoir rattaché à un expert
Je ne sais pas si c'est très clair...
Sinon tu peux rattacher quand un seul expert, cela ne me change rien, je
mets à conclu générale à la fin. C'est sans doute l'option la plus simple

A presto
Léonore
PS : j'ai encore fait une erreur de numéro de cote dans une fiche. Est-ce
qu'on pourra la rectifier avec les deux autres que je t'ai signalé l'autre
jour ? merci





Le mar. 4 mai 2021 à 12:25, Josselin Morvan ***@***.***> a
écrit :

> Est-ce ce que cela veut dire qu’il vaut mieux éviter l’automatisation,
> même pour les expertises n’ayant qu’un seul expert ?
>
> Envoyé de mon iPhone
>

**Comment by sardinecan** [comment]
l'ajout des attributs @ref est fait. Lorsqu'il n'y a un seul expert l'attribut @ref est renseigné, sinon la valeur de l'attribut est laissée vide. 
Il n'y a pas eu de regroupement de "conclusions", même lorsqu'il n'y a qu'un seul expert.
