### ISSUE TITLE
Verser les images dans Nakala

### ISSUE THREAD

**Issue by emchateau** [anrExperts/xpr#118]
Les numérisations des expertises ont été versées sur Sharedocs. Pour faciliter leur présentation dans l’interface, nous avons décidé de les publier par l’intermédiaire de Nakala pour les afficher en IIIF.
- [x] préparer un script de récupération
- [x] valider les orientations
- [x] verser les images
- [x] produire les manifestes

**Comment by emchateau** [comment]
Voir l’analyse préparée pour créer un script XQuery https://github.com/publicarchi/cbc/tree/master/testManifeste
(fichier md)

**Comment by sardinecan** [comment]
fait
