### ISSUE TITLE
Créer un repo github pour le schéma

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#124]
Cher @emchateau,

J'ai commencé à travailler sur le schéma xpr. Je voulais savoir si tu préférais qu'on crée un repo spécifique pour l'archiver, ou bien préfères-tu qu'on le mette dans le repo data ou xpr ?
Amitiés

**Comment by emchateau** [comment]
Salut, je pense qu’on peut le versionner avec les données. Le problème c’est que notre répertoire de données mériterait peut être une petite réorganisation.

**Comment by sardinecan** [comment]
done.
