### ISSUE TITLE
Conclusions d'experts

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#16]
Faut-il conditionner le champ "transcription de toutes les conclusions ou dispositifs de l'expertise" avec le champ "conclusion" ? par exemple : 
- si "accord" ou "désaccord" est coché => possibilité de renseigner une ou plusieurs conclusions
- si "aucune conclusion" est cochée => on masque le champ

Même s'il n'y a pas de conclusions à proprement parlé peut-on être amené à y renseigner quelque chose ?

**Comment by emchateau** [comment]
Lier les deux puis évaluer avec l’équipe pendant la phase de test

**Comment by emchateau** [comment]
Fait
