### ISSUE TITLE
Firefox et namespace

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#25]
Suite à l'ajout du namespace `xpr` dans le formulaire et les instances, Firefox refuse d'afficher le formulaire.

**Comment by sardinecan** [comment]
J'ai ajouté une branche `noNamespace` au répertoire git.
La branche master et noNamespace identique, à l'exception du namespace `xpr`.

**Comment by sardinecan** [comment]
Aucun problème rencontré avec Chrome et Safari. 
Version de Firefox : 66.0.3 (64 bits) (dernière au 12/04/2019)

**Comment by emchateau** [comment]
Il me semble avoir vu un très vieux bug qui parlait d’un problème de support des namespaces dans Firefox. Du coup, cela ne serait pas réglé...
Ce qui explique aussi que quand j’avais essayé les namespaces, cela ne fonctionnait pas !

**Comment by sardinecan** [comment]
Pour des essais ultérieurs, un exemple minimal (qui ne fonctionne pas avec ff) :
https://gist.github.com/sardinecan/9a29df0e1ee12f8bd647301d15cdc2a7

**Comment by sardinecan** [comment]
> Il me semble avoir vu un très vieux bug qui parlait d’un problème de support des namespaces dans Firefox. Du coup, cela ne serait pas réglé...
> Ce qui explique aussi que quand j’avais essayé les namespaces, cela ne fonctionnait pas !

Pourtant, d'après la doc de ff, ça devrait… 
>If the instance is not in the empty namespace (xmlns=""), then all binding expressions must use a prefix bound to the namespace. XPath 1.0 expressions do not have a default namespace, so a prefix must always be specified if the namespace is not the empty namespace.

**Comment by sardinecan** [comment]
Pour archivage, la solution est donnée ici, c'est un problème connu du moteur mozilla (qui ne se bouge pas visiblement pour le résoudre)
- [Unrecognized namespace prefixes](https://en.wikibooks.org/wiki/XSLTForms/XForms_1.1#Unrecognized_namespace_prefixes)
- [Problem with Namespace Axis in Firefox 3.0](https://en.wikibooks.org/wiki/XRX/XSLTForms_and_eXist#Problem_with_Namespace_Axis_in_Firefox_3.0)
- [User-Defined Functions](https://en.wikibooks.org/wiki/XSLTForms/XSLTForms_only_Extensions#User-Defined_Functions)

```xml
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:xf="http://www.w3.org/2002/xforms"
    xmlns:nfunc="http://example.net/xforms/new-functions/"
    nfunc:bogus="Workaround for FF's bug: https://bugzilla.mozilla.org/show_bug.cgi?id=94270">
</html>
