### ISSUE TITLE
Ajouter un champ "Nombre de vacations"

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#40]
L'entrée des dates de vacations ne suffit pas, puisqu'une même date peut correspondre à une ou à deux vacations (matin et après-midi le cas échéant).

ex. *Z1J434, 40* : dix dates de vacations rentrées, mais il y a eu 11 vacations (deux vacations le dernier jour, 05/03/1697)

**Comment by sardinecan** [comment]
Il me semble que c'est une des questions que nous avions posées implicitement avec @emchateau lorsque nous élaborions le modèle et que nous avions des interrogations quant à la description des  lieux de l'expertise. Sauf erreur de ma part, il avait été décidé que nous devions raisonner en terme de "vacation" et non de "date" ou de de "lieu", et que toutes les vacations devaient donc être décrites (date + lieu).

Ainsi, pour n vacations, nous devons en renseigner le même nombre dans le formulaire, même si effectivement plusieurs peuvent avoir une même date et un même lieu. @emchateau as-tu le même souvenir que moi sur ce point ?

Si nous décidons de raisonner par les dates, il faudra alors renseigner la quotité de vacation pour chacune (un champ de plus à remplir systématiquement).

**Comment by LeonoreLosserand** [comment]
il me semble qu'on raisonnait pas vacation et non par date, de mémoire...

**Comment by emchateau** [comment]
Je me souviens également que la discussion nous avait conduit à décider de raisonner en termes de vacations plutôt que de lieux ou de dates.
Cela a l’inconvénient de nécessiter la répétition des vacations lorsqu’elles ont lieu au même endroit. Je comprends que l’ajout d’un quantificateur simplifierai la saisie. Mais ce n’est pas du tout le même modèle de données.
Je vois deux solutions :
- travailler sur l’interface pour créer une vacation identique à celle précédemment entrée pour faciliter la saisie.
- travailler sur un modèle mixte qui permettrait de rassembler les vacations (pas propre et pb de cohérence)
Qu’en dites-vous ?

**Comment by LeonoreLosserand** [comment]
j'ai des dates de vacations qui disparaissent quand je scrolle, j'en avais 4 dans des lieux différents (campagne, parisfaubourg). J'ai dû enregistrer quand même, mais comme je ne parviens pas à revenir sur ce que j'ai saisi (il me semble que ce n'est pas encore possible), je ne sais pas si cela s'est quand même enregistré ou si c'est un bug de ma part
Merci

**Comment by emchateau** [comment]
La semaine prochaine vous aurez la révision. Cela me paraît effectivement nécessaire.

**Comment by Pohjola1** [comment]
Les deux solutions que tu proposes, Emmanuel, me semblent convenir : je pensais qu'on ne pouvait pas entrer deux fois la même date, ce qui me gênait pour renseigner correctement le champ.
