### ISSUE TITLE
Ajouter dans la liste des "Lieux de l'expertise" : 'Bureau du greffier'

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#41]
(en plus de 'Bureau des experts')

ex. *Z1J434, 40*

**Comment by sardinecan** [comment]
Avez-vous besoin des autres champs pour le bureau du greffier (voie, numéro de voie, précisions géographiques, etc.) ?

**Comment by Pohjola1** [comment]
A priori non.

**Comment by sardinecan** [comment]
done
