### ISSUE TITLE
Liste des expertises

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#42]
Le bug pouvant se présenter à Léonore, j'ajoute suite au mail de Juliette :
> Je n'arrive plus à accéder au formulaire via l'adresse http://localhost:8984/xpr/expertises/.
> J'ai bien lancé basex via le Terminal ; tout fonctionnait bien jusqu'aux environs d'11h30/12h. 
> Vous êtes peut-être en train d'y travailler ; je passe sur autre chose mais je vous envoie quand même une capture d'écran au cas où il y aurait un problème.

**Comment by sardinecan** [comment]
Il s'agit d'une erreur de notre part. Pour générer la liste des expertises, le système s'attendait à ne trouver qu'une seule date de vacation par expertise. La dernière expertise que tu as renseignée devait en comporter plusieurs et le système s'est retrouver en présence d'une séquence. 
J'ai corrigé le problème pour l'instant en lui demandant de n'afficher que la première date de vacation.

PS : pour récupérer la modification, il suffit de lancer l'application Git Desktop,  sélectionner, si ce n'est pas déjà le cas, 'xpr' dans l'onglet 'current repository', puis de cliquer sur 'fetch origin'

**Comment by LeonoreLosserand** [comment]
ola,
ça ne marche pas pour moi...
http://localhost:8984/xpr/expertises/
erreur de chargement de la page

merci et à bientôt
Léonore

**Comment by sardinecan** [comment]
as-tu bien lancer basexhttp avant d'essayer de te connecter à l'url de l'application ?

**Comment by LeonoreLosserand** [comment]
en effet, pardon autant pour moi, je reviens d'une semaine de vacances (ou presque) et l'atterrissage est rude...
merci beaucoup !!
léonore

**Comment by sardinecan** [comment]
done
