### ISSUE TITLE
Corriger : disparition des champs Nom / prénom / qualité dans la rubrique Parties

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#44]
Une fausse manipulation qui se répète mais difficile à expliquer précisément (cela m'est arrivé quatre ou cinq fois) fait disparaître les champs Nom / Prénom / Qualité dans la partie PARTIES.
Les champs dessous restent (avec menus déroulants), mais je ne peux plus indiquer le nom des parties.

_Voir Z1J 828, dossier 75_

**Comment by sardinecan** [comment]
J'ai jeté un coup d'œil rapidement (je suis sur le projet Condor cette semaine) mais je pense avoir identifié le problème : la disparitions se produit lorsque deux parties sont déjà déclarées et que tu supprimes des personnes ?
J'ai apporté un correctif que tu peux récupérer en faisant un fetch avec l'application GitDesktop, de la même manière que précédemment.
J'attends ton retour pour fermer (ou non !) cette issue.

**Comment by Pohjola1** [comment]
Merci Josselin. Ta description des circonstances me semble coller assez bien avec ce qui se passait ; j'ai récupéré le correctif, je vais voir si ça se reproduit ou non.
