### ISSUE TITLE
Ajouter un champ "Autre, à préciser" dans la rubrique Coût de l'expertise

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#45]
En plus des catégories 
Expert
Greffier
Roles
Papier et contrôle
etc.
figurent parfois des coûts exceptionnels (faux frais / voiture, par exemple), qu'il faudrait pouvoir mentionner. 

_(ils sont pour l'instant ajoutés en commentaire général sur l'expertise concernée)_

**Comment by sardinecan** [comment]
Faut-il rendre ce champ répétable ?

**Comment by Pohjola1** [comment]
Ce serait mieux, oui.

**Comment by emchateau** [comment]
On pourrait aussi se contenter d’un champ libre tout simple. À la condition qu’on ne souhaite pas faire de calcul avec

**Comment by sardinecan** [comment]
done
