### ISSUE TITLE
Corriger les IDs des expertises pour modification

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#49]
Précédemment, les `@xml:id` étaient générés uniquement à partir de l'élément `idno[@type='unitid']`, ce qui occasionne des erreurs pour la modification des fiches, car plusieurs expertises disposent de fait du même identifiant.

**Comment by sardinecan** [comment]
@emchateau, j'ai réalisé un script repriseId.xq sur le modèle de ce que tu as fait, qui met à jour la base xpr en corrigeant l'@xml:id, l'idno[@type='unitid'] (upper-case + no whitespace) et l'idno[@type='item'] (format-integer '000').

J'ai récupérer la bdd de Juliette et celle de Léonore pour le tester et vraisemblablement ça fonctionne, mais pourrais-tu y jeter un œil pour vérifier que rien ne m'échappe (pour le coup c'est mon premier script Xquery tout seul…)
Merci

**Comment by sardinecan** [comment]
NB : les nouvelles expertises saisies peuvent être modifiées, seules les anciennes sont donc concernées par ce problèmes.

**Comment by emchateau** [comment]
Je pense que par défaut on ne créait pas d’ID et qu’il faut un ID pour pouvoir modifier la fiche.
Dans ton script, tu changes la casse, comme il s’agit d’un id, j'aurais tendance à mettre tout en bas de casse (plus lisible). Il faudrait le faire partout car dans xpr.xqm je ne le faisais pas.
Dans tes fonctions tu as à chaque fois un replace de trop, l. 21 et 24

**Comment by sardinecan** [comment]
> Je pense que par défaut on ne créait pas d’ID et qu’il faut un ID pour pouvoir modifier la fiche.
Pour les test nous avions mis la valeur de l'unitid, et on n'a pas dû penser à changer ça avant de donner la main à Juliette et Léonore.

> Dans ton script, tu changes la casse, comme il s’agit d’un id, j'aurais tendance à mettre tout en bas de casse (plus lisible). Il faudrait le faire partout car dans xpr.xqm je ne le faisais pas.
Ok je m'en occupe

> Dans tes fonctions tu as à chaque fois un replace de trop, l. 21 et 24
C'est pour corriger dans la foulée quelques saisies erronées, par exemple, j'ai repéré un ou deux 'Z1J 343', au lieu de Z1J343 (sans espace) dans unitid, idem pour les item.

**Comment by sardinecan** [comment]
done
