### ISSUE TITLE
Modifier la structure du champ conclusion

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#51]
Actuellement : 
a/ accord
b/ désaccord
c/ sans conclusion
puis transcription des conclusions

Il serait plus logique d'avoir une structure comme proche de celle-ci :
a/ un seul expert
> aa/ conclusion : ………
> ab/ sans conclusion

b/ plusieurs experts
> ba/ accord
>> baa/ conclusion : ………
>> bab/ sans conclusion [à vérifier, mais je ne vois pas de cas où il y aurait plusieurs experts et pas de conclusion, à part dans le cas d'une expertise inachevée] 

> bb / désaccord
>> bba/ conclusion du premier expert  :
>> bbb/ conclusion du deuxième expert :
>> bbc/ [confirmer que le cas existe] conclusion du troisième expert :
>> bbd/ sans conclusion [idem, absence de conclusion semble contradictoire avec le désaccord, qui transparaît forcément dans une conclusion ; à confirmer]

**Comment by sardinecan** [comment]
Pour simplifier le cas des “sans conclusions”, pourrait-on utiliser le système suivant, pour les affaires impliquant plusieurs experts : 
- A) Accord
    - Conclusions
- B) Désaccord
    - Conclusions expert 1
    - Conclusions expert 2
    - Conclusions expert 3 (le cas échéant)=> c'est le cas du tiers expert ?
- C) Sans conclusions 
    - On le remonte d'un niveau par rapport à ta proposition car comme tu le remarques, s'il y a accord ou désaccord c'est que nous devrions avoir des conclusions, mais peut-on imaginer qu'elles manques (feuillets perdus, illisibles, etc.) ?

**Comment by Pohjola1** [comment]
Oui, ça me semble pouvoir fonctionner de cette façon.

**Comment by emchateau** [comment]
Fait
