### ISSUE TITLE
Ajouter un champ "Affaire accommodée" - "Affaire non terminée"

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#52]
Entre la partie Conclusions et le détail des coûts, ajouter un champ (case à cocher ?) "Affaire accommodée" et "Affaire non terminée", pour indiquer que l'affaire s'est terminée par un accord amiable entre les parties ou par une remise sans suite, sans que l'expertise n'aille jusqu'à son terme.

**Comment by emchateau** [comment]
Fait
