### ISSUE TITLE
bug pour l'ajout des parties, dates, etc... après MAJ

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#57]
j'ai fait une mise à jour tout à l'heure et depuis je ne parviens pas à rajouter des éléments sur la fiches (autre partie, dates, lieux...) pour y parvenir je dois enregistrer la fiche et revenir dessus...
voici le message d'erreur : 
XSLTForms Exception
--------------------------

Error evaluating the following XPath expression :

instance('xprRanges')/xpr:range[@type='role']

Error

[object Object]

**Comment by sardinecan** [comment]
C'est corrigé

**Comment by LeonoreLosserand** [comment]
Merci beaucoup Josselin pour la rapidité de réponse !
tout fonctionne
Bon week-end (pour ce qu'il en reste)

Léonore

Le sam. 6 juil. 2019 à 20:16, Josselin Morvan <notifications@github.com> a
écrit :
