### ISSUE TITLE
Évaluer l'itération des actions pour simplifier le formulaire

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#58]
https://www.w3.org/TR/xforms11/#action-iterated

**Comment by sardinecan** [comment]
notamment pour `
<xf:action ev:event="xforms-ready">
                <xf:setvalue ref="instance('xprSupplement')/xpr:categories/xpr:category[not(@type)]" value="concat(
                                instance('xprModel')/xpr:description/xpr:categories/xpr:category[1]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:categories/xpr:category[2]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:categories/xpr:category[3]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:categories/xpr:category[4]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:categories/xpr:category[5]/@type
                                )"/>
                <xf:setvalue ref="instance('xprSupplement')/xpr:objects/xpr:object[not(@type)]" value="concat(
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[1]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[2]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[3]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[4]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[5]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[6]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[7]/@type, ' ',
                                instance('xprModel')/xpr:description/xpr:procedure/xpr:objects/xpr:object[8]/@type
                                )"/>
        </xf:action>
`

**Comment by emchateau** [comment]
solutionné autrement XForms supporte string-join
