### ISSUE TITLE
changer les petits menus déroulants en cases à cocher

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#61]
Si possible limiter le scroll au max

**Acteurs de l'expertise/experts** 

- expert nommé en 
- expert nommé

**Acteurs de l'expertise/parties**

- Partie (requérante/opposante)
- Expert agissant pour cette partie
- partie présente
- partie intervenante 

**Procédure et cadre juridique**

- Origine de l’expertise/Déclenchement de l’expertise => si possible sur la même ligne (les deux cases à cocher)

**Conclusions/Bourse commune**

- Mention(s) de la bourse commune (des experts ou greffiers) et détail

**Comment by emchateau** [comment]
Fait en partie, après discussion.
