### ISSUE TITLE
message d'erreur

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#65]
Lorsque je souhaite revenir sur une fiche déjà complétée, voici ce qui apparait dans la fenêtre : 
XSLTForms Exception
Error dispatching event 'xforms-model-construct' :
xforms-link-exception
et je ne peux pas accéder à ladite fiche...
Cela depuis au moins mercredi ou jeudi...

merci !

**Comment by sardinecan** [comment]
ça semble traduire un problème d'accès à une des instances.
Comment cela s'est-il produit, as-tu fait une mise à jour ? 
Je suis dispo sur Skype si tu veux que nous regardions cela.
