### ISSUE TITLE
problème dans le champ Parties

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#67]
Les sélections disparaissent dans certains cas (réquérant / opposant ou choix d'expert par exemple).
Cela se produit en cours de saisie, avant enregistrement de la fiche ; je ne sais pas préciser davantage le contexte.

**Comment by Pohjola1** [comment]
Cela se produit en tout cas lorsqu'on ajoute une nouvelle partie, après avoir fait les sélections (requérant / opposant ou choix d'expert ; présent ou non) pour une première partie.

**Comment by sardinecan** [comment]
je suis sont le projet Condorcet cette semaine, mais, si ça vient de se produire, pourrais tu noter la fiche sur laquelle tu travaillais pour que je puisse retrouver/reproduire le contexte par la suite ?

**Comment by sardinecan** [comment]
ok

**Comment by Pohjola1** [comment]
Par exemple Z1J 833-2, dossier 15.
Mais ce n'est pas urgent. Je l'avais déjà repéré la semaine dernière ; je vérifie à chaque fois en attendant, c'est moins gênant qu'un champ texte.

**Comment by sardinecan** [comment]
C'est bon, je viens de le reproduire sur ma machine, j'essaie de régler ça aujourd'hui.
Q° avais-tu repéré ce phénomène avant ? et as-tu fait une mise à jour depuis la semaine dernière ?

**Comment by sardinecan** [comment]
Je suppose que tu as fait une mise à jour, car, pour une raison que j'ignore encore, ça semble lié aux boutons radio (ou cases à cocher) qui étaient auparavant des listes déroulantes.
Vraisemblablement les infos précédemment saisies ne sont pas supprimées, mais elle n'apparaissent plus à l'écran…
Ça le fait également pour les experts (si tu en ajoute un deuxième)

**Comment by Pohjola1** [comment]
Oui voilà, c'est depuis la mise à jour et la suppression des menus déroulants.
