### ISSUE TITLE
message d'erreur à l'ouverture 

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#68]
"XSLTForms Exception
--------------------------
Error dispatching event 'xforms-model-construct' :
xforms-link-exception"

c'est le message que j'ai quand j'ouvre la base
puis je ne peux que faire une exportation de la base (qui ne marche pas) 
ou "ajouter" une nouvelle fiche
help !

**Comment by sardinecan** [comment]
On voit ça sur skype ? je suis connecté. Je pense que tu as fait une mise à jour sur git ?
