### ISSUE TITLE
Ajouter une conclusion manuellement

### ISSUE THREAD

**Issue by Pohjola1** [anrExperts/xpr#72]
Dans les cas de désaccord des experts, il y a en fait **trois conclusions**, et non pas deux ; il faudrait donc ajouter un champ 'conclusion du tiers expert'.

**Comment by sardinecan** [comment]
Si tu as renseigné 3 experts dans la partie acteur, il devrait logiquement y avoir 3 champs conclusions (si la case désaccord est cochée), chacune avec le nom de l'expert auquel elle se rattache.

**Comment by Pohjola1** [comment]
En effet, pardon. Je n'avais pas eu de cas avec tiers expert depuis un moment et j'avais oublié ça. Il s'agissait d'un cas particulier, que j'essaie de retrouver pour comprendre (je suppose qu'il n'y avait pas de tiers expert mais tout de même une conclusion distincte). On peut clore le sujet, je te soumettrai le cas une fois que je l'aurai retrouvé si cela pose un problème de saisie malgré tout.

**Comment by sardinecan** [comment]
Aucun problème, dans ce cas, il nous sera possible d'ajouter un champ conclusion "à la main", en plus des autres. Je ne ferme pas l'issue pour que nous la gardions en tête, mais je vais le renommer.

**Comment by Pohjola1** [comment]
J'ai retrouvé la cause du problème : en remplissant le formulaire au fil de la lecture du pv, on remplit normalement les deux premiers experts, puis leurs conclusions, et seulement après le tiers, et à la toute fin sa conclusion à lui. Le fait d'avoir sélectionné "désaccord" avec seulement deux experts enregistrés crée deux champs conclusions, et le fait d'ajouter un tiers expert ensuite ne rajoute pas le 3e champ conclusion (il faut cocher "accord" puis à nouveau "désaccord" pour le faire apparaître). En sachant qu'il peut bien y avoir trois champs conclusion (ce que j'avais oublié quand j'ai ouvert cette discussion), on peut régler ça manuellement, mais si jamais il y a un moyen de corriger le problème facilement, ça faciliterait la saisie. (C'était donc vraiment un tout petit problème, mais au moins tu en as l'explication !)

**Comment by sardinecan** [comment]
Après coup je me suis douté que c'était le problème. C'est pas grand chose je vais automatiser le process :
Si tu as déjà cliqué sur "désaccord" et que tu ajoutes un tiers expert, son champ conclusion sera ajouté à la suite des deux autres.
Je te tiens informée lorsque c'est fait

**Comment by Pohjola1** [comment]
D'accord, merci !

Le jeu. 19 déc. 2019 à 15:09, Josselin Morvan <notifications@github.com> a
écrit :

**Comment by emchateau** [comment]
Fait
