### ISSUE TITLE
bug sur une fiche (gip)

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#75]
lorsque j'ouvre la fiche Z1J999/15 voici la message d'erreur qui persiste :
SLTForms Exception
--------------------------
Error dispatching event 'xforms-model-construct' :
xforms-link-exception

**Comment by sardinecan** [comment]
C'est une erreur d'identifiant : la Z1J999/15 a été mal cotée et est actuellement identifiée comme Z1J1003/15. De fait il existe donc deux Z1J1003/15 et le système ne sait pas laquelle choisir. 
Je viens de corriger son identifiant, il faudra que nous procédions à son remplacement dans ta BDD

**Comment by emchateau** [comment]
Réglé, deux fois la même fiche
