### ISSUE TITLE
[gip] faire apparaitre l'affichage de la liste après validation de fiche

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#76]
- une fois qu'on a validé les fiches, il y a une petite fenêtre texte où il faut cliquer ok (comme pour la bdd xpr), est-ce qu'on pourrait la supprimer (idem pour la bdd xpr) et surtout faire en sorte que la liste des pv apparaissent ensuite ? en effet, une fois cliqué sur ok, on reste sur la page du pv. Ca enregistre bien, mais je dois recliquer pour faire la fiche suivante.

**Comment by sardinecan** [comment]
Nous avions discuté de la fenêtre popup et du clic avec @emchateau et décidé de la garder car elle assure la validation et permet de contrôler que tout s'est bien déroulé. Je sais que dans 99% des cas elle indique que la ressource a bien été enregistrée, mais c'est un mal pour un bien.

Malheureusement, c'est pire avec la fiche prosopo, puisqu'il y a une popup de validation par personne ajoutée dans la base, mais s'il y a un problème, on est en mesure de l'identifier facilement. 

En revanche, on peut vous renvoyer vers la liste des expertises après le clic, je m'en occupe.

**Comment by sardinecan** [comment]
fait. vous pouvez faire un git pull avec Github Desktop

**Comment by emchateau** [comment]
Terminé
