### ISSUE TITLE
rajouter case conclusion pour estimation de chaque maison

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#77]
- pour les estimations de plusieurs maisons, il y a bien les cases pour leur prix qui apparaissent distinctement, mais je ne vois pas un espace pour noter chaque conclusion (petite description dont Michela a grand besoin si j'ai bien compris). Je ne sais plus si on a parlé de cela et si je me fais bien comprendre...

**Comment by Pohjola1** [comment]
Les descriptions qui précèdent l'estimation sont reportées dans la case conclusion, sans distinction des différents bâtiments (il faut seulement continuer à préciser comme avant de quel bâtiment on parle) : la distinction des champs n'est faite que pour le prix brut. La distinction permet de comparer les nombres, mais n'est pas nécessaire ni utile pour les descriptions textuelles.

**Comment by sardinecan** [comment]
Juliette a été plus rapide !!

**Comment by emchateau** [comment]
Fait
