### ISSUE TITLE
bug case à cocher bourses communes

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#78]
- pb déjà observé sur le bdd xpr, aussi dans gip : lorsqu'on revient sur une fiche, onglet conclusion, bourses communes : les cases à cochées si elles l'ont été ne le sont plus à la réouverture de la fiche ; si on recoche, les chiffres disparaissent...

**Comment by sardinecan** [comment]
C'est corrigé. vous pouvez faire un git pull avec l'application Github Desktop
