### ISSUE TITLE
lenteur d'affichage à l'écriture (bug perso ?)

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#79]
- lorsque j'écris dans les cases, le texte met du temps à s'afficher, je crois que c'est mon ordi qui n'a plus de place, mais est-ce que ne serait pas dû à autre chose par hasard ?

**Comment by sardinecan** [comment]
A priori, je n'ai pas ce problème, je laisse répondre @emchateau  et @Pohjola1 pour validation.

**Comment by emchateau** [comment]
Aucun problème moi non-plus

**Comment by Pohjola1** [comment]
Pour moi non plus, pas de problème.

**Comment by emchateau** [comment]
Problème lié aux performances du terminal de saisie. Résolu par la refactorisation.
