### ISSUE TITLE
rajout de case dns lieux

### ISSUE THREAD

**Issue by LeonoreLosserand** [anrExperts/xpr#80]
amélioration pour les lieux situé en banlieue et province : n'apparait que la case "précisions géographiques" alors que très souvent on a quand même un nom de rue en plus d'une précision géographique. serait-il possible de donner la même forme au carré "Lieux de l’expertise" aussi bien quand il s'agit de Paris que banlieue et province ? (rue du faubourg St Antoine par exemple) 
C'est sans doute pbtique parce qu'on ne l'a pas fait depuis le début

**Comment by sardinecan** [comment]
De mémoire nous n'avions pas mis ces champs parce qu'on ne souhaitait pas gérer les noms de rue hors de Paris. 
Si je me souviens bien, il avait même été question de ne renseigner que la ville et le département.
Effectivement, si nous modifions ce schéma il faudra aligner les anciennes fiches.
Je pense que c'est un peu l'objet de la réunion à venir ?

**Comment by sardinecan** [comment]
ajoute-t-on la paroisse pour la banlieue et la province ?

**Comment by LeonoreLosserand** [comment]
oui !

Le dim. 14 juin 2020 à 19:17, Josselin Morvan <notifications@github.com> a
écrit :

**Comment by rcarvais** [comment]
Léonore l’avait demandé mais je pense que ce n’est pas la peine.

 

De : Josselin Morvan [mailto:notifications@github.com] 
Envoyé : dimanche 14 juin 2020 19:17
À : anrExperts/xpr
Cc : rcarvais; Assign
Objet : Re: [anrExperts/xpr] rajout de case dns lieux (#80)

 

ajoute-t-on la paroisse pour la banlieue et la province ?

**Comment by sardinecan** [comment]
Pour les lieux indéterminés, nous avons les champs : 
- Voie
- N° de voie
- Précisions géographiques

Doit-on ajouter d'autres champs ? en toute logique si nous connaissons la ville ou le département, ce lieu ne devrait pas être coché indéterminé ? nous pouvons en revanche ajouter la paroisse ?

**Comment by LeonoreLosserand** [comment]
pour les lieux indéterminés c'est suffisant (tu peux même à mon avis ne
laisser que précision géographique parce que par définition, c'est
indéterminé.
Je l'ai utilisé l'autre jour (la 1ère fois peut-être) parce que c'était au
bureau du notaire dont l'adresse n'était pas précisée...
Merci !

Le dim. 14 juin 2020 à 19:22, Josselin Morvan <notifications@github.com> a
écrit :

**Comment by emchateau** [comment]
Le formulaire a été modifié ainsi que les données. Il reste à normaliser les données.
https://github.com/anrExperts/data/tree/b20065b389bffca9cf7a5accaf88b82cc4786e38
