### ISSUE TITLE
résoudre problème label pour les estimations de lieux

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#84]
Voir p.ex z1j1000d023
Vraisemblablement pour les lieux qui sont hors de Paris.

**Comment by emchateau** [comment]
A été discuté en commun.
Un script updateExpertisesPlaces pour ajouter les champs manquants dans les lieux.

**Comment by emchateau** [comment]
https://github.com/anrExperts/data/tree/b20065b389bffca9cf7a5accaf88b82cc4786e38
