### ISSUE TITLE
lieu par défaut

### ISSUE THREAD

**Issue by sardinecan** [anrExperts/xpr#9]
Mettre par défaut Paris pour les lieux de l'expertise

**Comment by sardinecan** [comment]
@emchateau 
Je viens de le faire. En revanche, je ne le remets plus à 0 lorsqu'on ajoute un lieu, partant du principe qu'il y a de grande probabilité de le second lieu soit à proximité ?

**Comment by emchateau** [comment]
En général, lorsque les lieux sont mitoyens on aura probablement une seule adresse à renseigner puisqu’il est rare que les n° soient employés. Je crois qu’il vaut mieux supprimer les valeurs pour le moment.
Ce sera ensuite à évaluer.

Emmanuel

**Comment by sardinecan** [comment]
done
