### ISSUE TITLE
Produire un schéma

### ISSUE THREAD

**Issue by emchateau** [anrExperts/xpr#90]
Pour faciliter les contrôles, on a besoin d’un schéma

**Comment by sardinecan** [comment]
@emchateau le schema est fait, est-ce que je rajoute la documentation (fichier xprDocumentationZ1j sur Google drive) ? J'ai hésité à la mettre car elle correspond au formulaire, mais au pire on peut faire un docx2tei et le rajouter rapidement ?

**Comment by emchateau** [comment]
Tu veux dire intégrer la documentation que nous avions dans le fichier GD dans le schéma ? Idéalement oui

**Comment by sardinecan** [comment]
Ça marche !

**Comment by sardinecan** [comment]
done
