### ISSUE TITLE
Script importation des images dans Nakala

### ISSUE THREAD

**Issue by emchateau** [anrExperts/xpr#95]
Préparer un script d’importation des images dans Nakala en XQuery qui utilise l’API de Nakala.

Plusieurs options sont possibles:
- utiliser le webdav de ShareDocs
- ou bien travailler localement avec une archive
Compte tenu de l’importance de l’archive, il serait préférable de travailler côté serveur.

Dépendance #96

**Comment by sardinecan** [comment]
fait avec script julia
