### ISSUE TITLE
Tester la rotation des images dans Nakala

### ISSUE THREAD

**Issue by emchateau** [anrExperts/xpr#96]
Les images chargées sur Sharedocs utilisent parfois un paramètre de rotation. Le standard n’était pas supporté par le serveur IIIF de Nakala. Depuis le passage à Cantaloupe, le problème devrait être réglé. Toutefois, l’image déjà chargée n’a pas été rétablie.
- [ ] tester
- [ ] communiquer avec Huma-Num en cas de pb

**Comment by sardinecan** [comment]
les images ont été retournées à la main avant d'être déposées sur Nakala
